### ISSUE TITLE
What exactly does 'archiving' mean in this case? 

### ISSUE THREAD

**Issue by COLABORATI** [bueltge/Archive#8]
It is not clear what exactly happens to a post when it is archived. 
Is it tar gzipped into a directory an dremoved from the database?
Will there be a term attached to the post?
Or does "archive" mean that the post is just "unpublished"?
Please explain the concept of "archiving" in this context, thank you very much!

**Comment by bueltge** [comment]
The post change only his post type, it is not a default post type from the core, like post, page, attachment. After archiving the post have the same data, same post meta data - only the post type is archive and thats is the point, that is not in default loops on front end and back end, only on a single back end UI only for this type and a custom loop for archive.
The links, relationship to attachments leaves also, no changes. The post type is on default not public, but is published.

Maybe this helps you?
