### ISSUE TITLE
Links to /archiv/webpage not working

### ISSUE THREAD

**Issue by pospiech** [bueltge/Archive#9]
I am using the plugin on the latest wordpress 4.7.2.
I defined the archive pages a longer time ago.
I can set up a page that shows all the archiv links. 
However none of the links work.
The pages itself still exist.

**Comment by bueltge** [comment]
I have tested this now and it works. My shortcode list the Title of the archive posts and link it right. Please check inside the back end that the post inside the Archive Post type exist.

**Comment by pospiech** [comment]
All articles are visible in the backend, and I can edit each post:
![2017-02-02 22_19_21-archiv matthias pospiech wordpress](https://cloud.githubusercontent.com/assets/1280544/22568900/d582a090-e995-11e6-9cc1-9b81bd54267d.png)

However the website does not know the page:
![2017-02-02 22_23_02-seite wurde nicht gefunden - matthias pospiech](https://cloud.githubusercontent.com/assets/1280544/22568994/386b4162-e996-11e6-8137-b195431ae6bf.png)

The link generated by the shortcode is correct. However the page rewrite does not seem to work.

**Comment by pospiech** [comment]
You can close the issue. I was a duplicate entry in the .htaccess file. The mod rewrite was confused...

**Comment by bueltge** [comment]
Great. Thanks for your feedback.
